version: "3"
services:
  zookeeper:
    container_name: zookeeper
    build: dockerfile-files/zookeeper
    ports:
     - '2181:2181'
    network_mode: host
  kafka:
    container_name: kafka
    build: dockerfile-files/kafka
    ports:
      - '9092:9092'
    network_mode: host
    depends_on:
      - zookeeper
  topics:
    container_name: topics
    build: dockerfile-files/topics-kafka
    ports:
      - '9092:9092'
    depends_on:
      - kafka
    network_mode: host
  mongo:
    container_name: mongo
    build: dockerfile-files/mongo
    ports:
      - '27017:27017'
    network_mode: host
  spark:
    container_name: spark
    build: dockerfile-files/spark
    network_mode: host
    environment:
      - SPARK_HOME=/main/spark-3.1.2-bin-hadoop2.7
    depends_on:
      - kafka
      - topics
      - mongo
  flask-server:
    container_name: flask-server
    build: dockerfile-files/flask-server
    ports:
      - '5000:5000'
    network_mode: host
    environment:
      - PROJECT_HOME=/main/bdfi-practicafinal
    depends_on:
      - spark