version: "3"
services:
  zookeeper:
    build: dockerfile-files/zookeeper
    ports:
      - '2181:2181'
    network_mode: host
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    build: dockerfile-files/kafka
    ports:
      - '9092:9092'
    network_mode: host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  topics:
    build: dockerfile-files/topics-kafka
    depends_on:
      - kafka
    network_mode: host
  mongo:
    build: dockerfile-files/mongo
    ports:
      - '27017:27017'
    network_mode: host
  spark:
    build: dockerfile-files/spark
    network_mode: host
    environment:
      - SPARK_HOME=/main/spark-3.1.2-bin-hadoop2.7
    depends_on:
      - kafka
      - topics
      - mongo
  flask-server:
    build: dockerfile-files/flask-server
    ports:
      - '5000:5000'
    network_mode: host
    environment:
      - PROJECT_HOME=/main/bdfi-practicafinal
    depends_on:
      - spark