apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: worker2
  name: worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: worker2
    spec:
      containers:
      - env:
        - name: SPARK_HOME
          value: /main/spark-3.1.2-bin-hadoop2.7
        image: worker2
        imagePullPolicy: ""
        name: worker2
        ports:
        - containerPort: 8080
        - containerPort: 7000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
