version: "3"
services:
  zookeeper:
    image: gcr.io/bdfi-367411/bdfi-zookeeper:2
    ports:
     - '2181:2181'
    network_mode: host
  kafka:
    image: gcr.io/bdfi-367411/bdfi-kafka:2
    ports:
      - '9092:9092'
    network_mode: host
    depends_on:
      - zookeeper
  topics:
    image: gcr.io/bdfi-367411/bdfi-topics-kafka:2
    ports:
      - '9092:9092'
    depends_on:
      - kafka
    network_mode: host
  mongo:
    image: gcr.io/bdfi-367411/bdfi-mongo:2
    ports:
      - '27017:27017'
    network_mode: host
  spark:
    image: gcr.io/bdfi-367411/bdfi-spark-m:3
    ports:
      - '8080:8080'
      - "7077:7077"
    network_mode: host
    environment:
      - SPARK_HOME=/main/spark-3.1.2-bin-hadoop2.7
      - KAFKA_HOST=localhost
      - KAFKA_PORT=9092
      - MONGO_PORT=27017
      - MONGO_HOST=localhost
      - SPARK_HOST=localhost
    depends_on:
      - kafka
      - topics
      - mongo
  worker1:
    image: gcr.io/bdfi-367411/bdfi-spark-w:3
    ports:
      - '8081:8080'
      - "7000:7000"
    network_mode: host
    environment:
      - SPARK_HOME=/main/spark-3.1.2-bin-hadoop2.7
      - SPARK_HOST=localhost
    depends_on:
      - spark
  worker2:
    image: gcr.io/bdfi-367411/bdfi-spark-w:3
    ports:
      - '8082:8080'
      - "7001:7000"
    network_mode: host
    environment:
      - SPARK_HOME=/main/spark-3.1.2-bin-hadoop2.7
    depends_on:
      - spark
  flask-server:
    image: gcr.io/bdfi-367411/bdfi-flask-server:2
    ports:
      - '5000:5000'
    network_mode: host
    environment:
      - PROJECT_HOME=/main/bdfi-practicafinal
      - MONGO_PORT=27017
      - MONGO_HOST=localhost
      - KAFKA_HOST=localhost
    depends_on:
      - spark