apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-server
  name: flask-server
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    io.kompose.service: flask-server
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  type: NodePort
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
    nodePort: 30017
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  type: NodePort
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
    nodePort: 30181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  type: NodePort
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    nodePort: 30092
  selector:
    io.kompose.service: kafka
status:
  loadBalancer: {}  
---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
#     kompose.version: 1.21.0 (992df58d8)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: topics
#   name: topics
# spec:
#   ports:
#   - name: "topics-9092"
#     port: 9092
#     targetPort: 9092
#   selector:
#     io.kompose.service: topics
# status:
#   loadBalancer: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
#     kompose.version: 1.21.0 (992df58d8)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: spark
#   name: spark
# spec:
#   type: NodePort
#   ports:
#   - name: "7077"
#     port: 7077
#     targetPort: 7077
#     nodePort: 30077
#   selector:
#     io.kompose.service: spark
# status:
#   loadBalancer: {}