apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spark
  name: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: spark
    spec:
      containers:
      - env:
        - name: SPARK_HOME
          value: /main/spark-3.1.2-bin-hadoop2.7
        image: gcr.io/bdfi-367411/bdfi-spark:1
        imagePullPolicy: ""
        name: spark
        ports:
        - containerPort: 7077
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
